### ISSUE TITLE
can not add Smithsonian connector

### ISSUE THREAD

**Issue by matrixknight** [microsoft/PowerPlatformAdvocacyWorkshops#3]
in Lab 4, I can not add a custom connector named Smithsonian .
![image](https://user-images.githubusercontent.com/707890/193465452-ed8ff5a4-c6fc-41dd-a379-23c4530080fc.png)

**Comment by Laskewitz** [comment]
Hi @matrixknight - 

It seems like something is blocking the connector from appearing in your app: 

* Did you publish the connector in the same environment as the Power App? 
* Did you run this workshop lab in your own developer tenant where you are the admin? Or did you do it in your company tenant? In the last case, there could be a [DLP policy](https://learn.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention) in the way.

**Comment by Laskewitz** [comment]
Hi @matrixknight - Can you comment on the respons above?

**Comment by Laskewitz** [comment]
Closed due to inactivity. Feel free to reopen the issue later when you can comment on the questions above.
